<?php

/**
* Implementation of hook_wysiwyg_plugin().
*/
function youtube_colorbox_wysiwyg_plugin($editor) {
  if ($editor == 'ckeditor') {
    return array(
      'youtube_video' => array(
        'name' => 'Youtube video',
        'description' => 'Open embed youtube video in colorbox',
        'path' => drupal_get_path('module', 'youtube_colorbox') . '/ckeditor-plugins/',
        'load' => TRUE,
        'buttons' => array(
          'youtube_video' => 'Insert Youtube video',
        ),
      ),
    );
  }
} 
